### PR TITLE
upstream added isstring to bytestring.builder

### PR DESCRIPTION
**Pull request by dradetsky**
From a fresh install of ghc & cabal-install, compile breaks with

```
[ 1 of 10] Compiling System.Posix.ARX.BlazeIsString ( System/Posix/ARX/BlazeIsString.hs, dist/build/System/Posix/ARX/BlazeIsString.o )

System/Posix/ARX/BlazeIsString.hs:10:10:
    Duplicate instance declarations:
      instance IsString Blaze.Builder
        -- Defined at System/Posix/ARX/BlazeIsString.hs:10:10
      instance IsString Blaze.Builder
        -- Defined in `bytestring-builder-0.10.6.0.0:Data.ByteString.Builder'
```

As far as I can tell (not really knowing haskell), the isString isn't necessary anymore, as it's more or less the same as the one that's been added in the new Data.ByteString.Builder (`P.primMapListFixed P.char8` vs `P.primMapListBounded P.charUtf8`).

I haven't actually tested this yet. It may break the program.

### CODE REVIEW

**Comment by solidsnack** [comment]
I made some changes to this branch to get it to compile and ran some commands. Please merge my branch with yours and then I'll merge this into master and run the full test suite (which I must find). Thanks for taking the time to work on this old program.

**Comment by dradetsky** [comment]
It didn't compile for you? Weird. How were you compiling it? I'm on ubanto 15.04 w/ghc 7.6.3 fwiw. Ran make and it went fine. Also cabal build or install (i forget which) went fine too.

**Comment by dradetsky** [comment]
Anyway, merged your branch. Still `make`'s ok on my box.

**Comment by solidsnack** [comment]
The error I saw was because `System.Exit` defines a `die` now. In `Data.Attoparsec`, the modules I was using are deprecated so I fixed those as well.

**Comment by dradetsky** [comment]
Odd. Are you using a newer ghc or newer haskell stdlib? (whatever it's
called; prelude?)

**Comment by solidsnack** [comment]
It's all new since I just got a new computer.

**Comment by dradetsky** [comment]
colleage: "it doesn't work on my box. what MRI version do you have?"

solidsnack: "I got a new computer."

colleague: "Wait, what?"

solidsnack: (silence)

**Comment by solidsnack** [comment]
Well, I just mean: all the Haskell stuff on my computer is very new.

**Comment by dradetsky** [comment]
I was just making a joke. No offense intended.

I mentioned previously that I had ghc 7.6.3 (the default for ubanto), and
that I'd installed it and all the cabal deps like 12 hours before filing
the pr. Do you have a newer ghc?

**Comment by solidsnack** [comment]
```
:;  ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.1
```

**Pull request merged**
